-- MySQL Script generated by MySQL Workbench
-- Пт. 07 авг. 2015 05:13:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dispatching_office
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dispatching_office
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dispatching_office` DEFAULT CHARACTER SET utf8 ;
USE `dispatching_office` ;

-- -----------------------------------------------------
-- Table `dispatching_office`.`users_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispatching_office`.`users_groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `group_name` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dispatching_office`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispatching_office`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `password` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `fullname` TEXT NULL DEFAULT NULL COMMENT '',
  `group_id` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_users_1`
    FOREIGN KEY (`group_id`)
    REFERENCES `dispatching_office`.`users_groups` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_users_1_idx` ON `dispatching_office`.`users` (`group_id` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `dispatching_office`.`order_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispatching_office`.`order_status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dispatching_office`.`workers_specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispatching_office`.`workers_specialization` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dispatching_office`.`workers_regions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispatching_office`.`workers_regions` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dispatching_office`.`workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispatching_office`.`workers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `fullname` TEXT NULL DEFAULT NULL COMMENT '',
  `phone` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `region` INT(11) NULL DEFAULT NULL COMMENT '',
  `specialization` INT(11) NULL DEFAULT NULL COMMENT '',
  `sub_specialization` TEXT NULL DEFAULT NULL COMMENT '',
  `count_done` INT(11) NULL DEFAULT NULL COMMENT '',
  `count_inwork` INT(11) NULL DEFAULT NULL COMMENT '',
  `count_wasunavailable` INT(11) NULL DEFAULT NULL COMMENT '',
  `count_waschanged` INT(11) NULL DEFAULT NULL COMMENT '',
  `count_notperformed` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_workers_1`
    FOREIGN KEY (`specialization`)
    REFERENCES `dispatching_office`.`workers_specialization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_workers_2`
    FOREIGN KEY (`region`)
    REFERENCES `dispatching_office`.`workers_regions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_workers_1_idx` ON `dispatching_office`.`workers` (`specialization` ASC)  COMMENT '';

CREATE INDEX `fk_workers_2_idx` ON `dispatching_office`.`workers` (`region` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `dispatching_office`.`order_advert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispatching_office`.`order_advert` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dispatching_office`.`order_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispatching_office`.`order_category` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `dispatching_office`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispatching_office`.`order` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `fullname` TEXT NULL DEFAULT NULL COMMENT '',
  `phone` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `advert_source` INT(11) NULL DEFAULT NULL COMMENT '',
  `reason` TEXT NULL DEFAULT NULL COMMENT '',
  `work_cat` INT(11) NULL DEFAULT NULL COMMENT '',
  `link_worker` INT(11) NULL DEFAULT NULL COMMENT '',
  `work_datetime` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `append_datetime` TIMESTAMP NULL DEFAULT NULL COMMENT '',
  `status` INT(11) NULL DEFAULT NULL COMMENT '',
  `link_user_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `archive` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_order_1`
    FOREIGN KEY (`link_user_id`)
    REFERENCES `dispatching_office`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_2`
    FOREIGN KEY (`status`)
    REFERENCES `dispatching_office`.`order_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_3`
    FOREIGN KEY (`link_worker`)
    REFERENCES `dispatching_office`.`workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_4`
    FOREIGN KEY (`advert_source`)
    REFERENCES `dispatching_office`.`order_advert` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_5`
    FOREIGN KEY (`work_cat`)
    REFERENCES `dispatching_office`.`order_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_order_1_idx` ON `dispatching_office`.`order` (`link_user_id` ASC)  COMMENT '';

CREATE INDEX `fk_order_2_idx` ON `dispatching_office`.`order` (`status` ASC)  COMMENT '';

CREATE INDEX `fk_order_3_idx` ON `dispatching_office`.`order` (`link_worker` ASC)  COMMENT '';

CREATE INDEX `fk_order_4_idx` ON `dispatching_office`.`order` (`advert_source` ASC)  COMMENT '';

CREATE INDEX `fk_order_5_idx` ON `dispatching_office`.`order` (`work_cat` ASC)  COMMENT '';


-- -----------------------------------------------------
-- Table `dispatching_office`.`workers_sub_specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dispatching_office`.`workers_sub_specialization` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(45) NULL DEFAULT NULL COMMENT '',
  `main_specialization` INT(11) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_workers_sub_specialization_1`
    FOREIGN KEY (`main_specialization`)
    REFERENCES `dispatching_office`.`workers_specialization` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_workers_sub_specialization_1_idx` ON `dispatching_office`.`workers_sub_specialization` (`main_specialization` ASC)  COMMENT '';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
